### DISCUSSION TITLE
Get rid of okay confirmation

### DISCUSSION THREAD

**Discussion by elmar-hinz** [keatontaylor/alexa-actions#158] [General]
### Feature request

The dialogue should be:

- Alexa: "Do you like dogs?"
- You: "Yes"
- Alexa: "Cool, I like dogs too"

The dialogue is:

- Alexa: "Do you like dogs?"
- You: "Yes"
- Alexa: "Okay"
- Alexa: "Cool, I like dogs too"

Wanted:

An option to suppress the automatic "okay" confirmation, if you want to handle the confirmation yourself. Something like this:

```
  - service: script.activate_alexa_actionable_notification
    data:
      text: Yes or no?
      suppress_confirmation: True
      event_id: hello_world
      alexa_device: media_player.<Your Media Player>
```

**Comment by elmar-hinz** [comment]
Technical considerations

The `OK` seems to be worded in `language_strings.json`.  Maybe it could be a workaround to temporarily set the value to an empty string.

Better, if `ask_sdk_core` has an API to control this. I guess the behaviour is originating there. `OK` is not actively called within `lambda_function.py` at least.

**Comment by DEADSEC-SECURITY** [comment]
This is fixed under the branch. Pending testing @elmar-hinz. If you could also give it a try and let me know if you find bugs

**Comment by DEADSEC-SECURITY** [comment]
Im fixing bugs though so might not work yet

**Comment by elmar-hinz** [comment]
One concern per commit. Please just don't mix bug fixing and features into one commit. It's difficult to track.

**Comment by DEADSEC-SECURITY** [comment]
Done fixed. Did some refactoring too cuz it was hard debugging the original code.
In my example I call the service like this.
![image](https://user-images.githubusercontent.com/45077772/210636788-b7e39330-fc3a-4665-b71f-9bae94f21315.png)

My script looks like this:
```
alias: Alexa Home Voice Ask
description: Activates an actionable notification on a specific echo device
fields:
  text:
    description: The text you would like alexa to speak.
    example: What would you like the thermostat set to?
  event_id:
    description: Correlation ID for event responses
    example: ask_for_temperature
  suppress_confirmation:
    description: If it should supress the Okay default response confirmation
    example: true
  alexa_device:
    description: Alexa device you want to trigger
    example: media_player.bedroom_echo
sequence:
  - service: input_text.set_value
    data:
      entity_id: input_text.alexa_actionable_notification
      value: >-
        {"text": "{{ text }}", "suppress_confirmation": "{{
        suppress_confirmation }}", "event": "{{ event_id }}"}
  - service: media_player.play_media
    data:
      entity_id: "{{ alexa_device }}"
      media_content_type: skill
      media_content_id: amzn1.ask.skill.87fb0d7f-dd0b-4bd1-92ef-3f59187374ae
mode: single
```
