### DISCUSSION TITLE
Blueprints

### DISCUSSION THREAD

**Discussion by elmar-hinz** [keatontaylor/alexa-actions#163] [Ideas]
I just discovered a new corner of HA, Blueprints. One of the few prebuilt blueprints is actually closely related to the topic of *actionable notifications*. They call it *confirmable notifications* and it is targeted do Smartphones.

I think it could bring some progress to offer this kind of user friendly configuration for *actionable notifications * as well.

<img width="703" alt="Screenshot 2023-01-13 at 23 18 25" src="https://user-images.githubusercontent.com/1227339/212430175-0b5166ed-28d5-4e26-bf7e-4d033ac4764c.png">
<img width="693" alt="Screenshot 2023-01-13 at 23 22 38" src="https://user-images.githubusercontent.com/1227339/212430252-a0bbf428-b32e-4fd5-bf87-6cd5b423d6b3.png">

**Comment by elmar-hinz** [comment]
Path the the file behind the form:

`/config/blueprints/script/homeassistant/confirmable_notification.yaml`

**Comment by DEADSEC-SECURITY** [comment]
Yup I use this too, when Im far away from my alexa it send a notification to my phone. 
Yes I agree we should make a blueprint for this, would reduce issues due to miss configuration etc.

**Comment by DEADSEC-SECURITY** [comment]
What do you think of this @elmar-hinz 
```
alias: Alexa Home Voice Ask
description: Activates an actionable notification on a specific echo device
fields:
  text:
    description: The text you would like alexa to speak.
    example: What would you like the thermostat set to?
  event_id:
    description: Correlation ID for event responses
    example: ask_for_temperature
  suppress_confirmation:
    description: If it should supress the Okay default response confirmation
    example: true
  alexa_device:
    description: Alexa device you want to trigger
    example: media_player.bedroom_echo
sequence:
  - service: input_text.set_value
    data:
      entity_id: input_text.alexa_actionable_notification
      value: >-
        {"text": "{{ text }}", "suppress_confirmation": "{{suppress_confirmation }}", "event": "{{ event_id }}"}
  - service: media_player.play_media
    data:
      entity_id: "{{ alexa_device }}"
      media_content_type: skill
      media_content_id: ID
mode: single
```

Still have to make it into a blueprint but what do you think of that structure for a script blueprint?
