### ISSUE TITLE
Can't get SSML to work

### ISSUE THREAD

**Issue by drthanwho** [keatontaylor/alexa-actions#10]
I've tried your example as is and many other examples from the documentation but none of them work. 

It just says  
> Sorry, I couldn't do what you asked

**Comment by keatontaylor** [comment]
Yep, just looked at it, seems the double quotes are messing things up.

Try this:
```
    action:
      - service: script.activate_alexa_actionable_notification
        data:
          text: "<amazon:effect name='whispered'>The front door has been unlocked for 5 mins, would you like me to lock it?</amazon:effect>"
          event_id: 'actionable_notification_lock_left_unlocked'
          alexa_device: 'media_player.living_room_echo'
```
