### ISSUE TITLE
INPUT TEXT copied into config.yaml has a parsing error

### ISSUE THREAD

**Issue by jonniepanda** [keatontaylor/alexa-actions#104]
###  For all support requests it is strongly recommend you join the #alexa-actionable-notifications discord channel for assistance. Myself and others are able to help you in real-time with issues.  [Discord Invite Link](https://discord.gg/AWgE6g)

For all other issues and feature requests, please replace this text with your issue or feature request. Thank you so much for all the support!

OK - tried the discord, but the invite has expired apparently so will post here and cross my fingers.

I've followed Mark Watt Tech video that uses this source. When I copy and paste... 

```
input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}' 
```

...into configuration.yaml the last line comes up with a parsing error - **Incorrect type. Expected "integer".**

I think this is causing me issues further down stream, as when I ask Alexa to Open Custom Actions, she replies, "There was a problem with the requested skills response"

Can anyone offer any guidance on what the parser is moaning about?

Thanks in advance
