### ISSUE TITLE
Problems with ResponseNone automation

### ISSUE THREAD

**Issue by calcioscacchi** [keatontaylor/alexa-actions#111]
Hi there. I'm just new with actionable notifications, but my project is step by step taking a form.

The target is a notification as this: "Tomorrow the plastic garbage will be collected. Did you take the garbage outside?"
If yes, nothing happens.
If the answer will be "no" or no answer is given, an automation will ask the same question in a 10 minutes.

How to do that:

My project is quite simple: I have a input.boolean that I toggle with a scheduler every week. (the garbage is collected every 2 weeks, so in week 1 the boolean is off and the week 2 the boolean will be on).
An automation triggered by the "on" state of the input.boolean  calls the "plastic garbage" script, wich contains the actionable notification.

If no or none, another automation (1 for NO and 1 for None, of course ;)) calls back the script with a delay of 10 minutes.

This is how magic happens. Now the problem:

The automations for RespondeNo and ResponseNone are identical, but the ResponseNo works, the RespondeNone is not working, I mean that seems that it's not triggered.

```
-alias: "Buttare la plastica No"
 trigger:
   -platform: event
    event_type: alexa_actionable_notification
    event_data:
    event_id: rifiuti_plastica
    event_response_type: ResponseNo
  action:
   -service: notify.alexa_media_echo_dot_studio
    data:
    message: te lo ricorderò a breve.
    data:
    type: tts
   -delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
   -service: script.buttare_la_plastica
```

```
-alias: "Buttare la plastica No"
 trigger:
   -platform: event
    event_type: alexa_actionable_notification
    event_data:
    event_id: rifiuti_plastica
    event_response_type: ResponseNone
  action:
   -service: notify.alexa_media_echo_dot_studio
    data:
    message: te lo ricorderò a breve.
    data:
    type: tts
   -delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
   -service: script.buttare_la_plastica
```

And there is the script:

```
alias: Buttare la plastica
sequence:
  - service: script.activate_alexa_actionable_notification
    data:
      text: Domani ritireranno la plastica. Avete portato fuori il sacco?
      event_id: rifiuti_plastica
      alexa_device: media_player.echo_dot_studio
mode: single
```

Some advices? Thanks.
