### ISSUE TITLE
alexa skill does not work correctly.. skill triggers but echo says nothing

### ISSUE THREAD

**Issue by MrThiemann** [keatontaylor/alexa-actions#125]
Hey Community,

I hope I'm in the right place with my problem...

For some time my "custom action" hasn't worked "reasonably" anymore.
At the moment I don't know what information you need. Tell me and I'll provide you with everything!

----

The problem is that the script is triggered somehow, but doesn't automatically trigger on an echo.

I basically have to give the command (start custom actions) first.
then I also see the updated input_text

I just started a test event. As you can see it triggers but no echo is activated
<img width="1118" alt="Bildschirmfoto 2022-09-27 um 07 04 53" src="https://user-images.githubusercontent.com/54147030/192436593-8f0bbeee-c9da-434c-a0b8-b7ff5af52d40.png">

if it should be helpful, here is my script and the input_text

```
description: Activates an actionable notification on a specific echo device
fields:
  text:
    description: The text you would like alexa to speak.
    example: What would you like the thermostat set to?
  event_id:
    description: Correlation ID for event responses
    example: ask_for_temperature
  alexa_device:
    description: Alexa device you want to trigger
    example: media_player.bedroom_echo
sequence:
  - service: input_text.set_value
    data:
      entity_id: input_text.alexa_actionable_notification
      value: "{\"text\": \"{{ text }}\", \"event\": \"{{ event_id }}\"}"
  - service: media_player.play_media
    data_template:
      entity_id: "{{ alexa_device }}"
      media_content_type: skill
      media_content_id: amzn1.ask.skill.xxx-xxx-xxx-xxx-xxx
mode: single
```

```
alexa_actionable_notification:
  name: Alexa Actionable Notification Holder
  max: 255
  initial: '{"text": "Dies ist ein Test des Alexa-Skills. Hat es funktioniert?", "event": "actionable.skill.test"}'
```

---

even if I start a call service manually, the state is changed, but the echo remains silent

<img width="1118" alt="Bildschirmfoto 2022-09-27 um 07 19 20" src="https://user-images.githubusercontent.com/54147030/192438626-fa6da5ca-58c6-4d64-9fa2-1e77883b16e9.png">

<img width="1155" alt="Bildschirmfoto 2022-09-27 um 07 19 29" src="https://user-images.githubusercontent.com/54147030/192438644-bad02d28-aeb4-4252-85cb-3258506807fa.png">

---

I've been at it for 3 days now and really don't know what else I could do.

I deleted the skill and created it again.
the connection between alexaApp and skill was cut and reconnected.....
