### ISSUE TITLE
[Bug]: Event not firing, no reaction on Echo BUT can reach skill via invocation name and Alexa routine

### ISSUE THREAD

**Issue by rhmunich** [keatontaylor/alexa-actions#214]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

github@hochstatter.de

### What happened?

I set up the Alexa Actions skill multiple times following exactly the installation instructions on Github but keep having the following issue:

The problem is that there is no reaction from the specified Alexa device when using the `script.activate_alexa_actionable_notification`  (i.e. no announcement on my Echo Dot and also no activity in the developer tools listening to the event `alexa_actionable_notifications`). I tried with several echo devices but no success. (They are all just Echo Dots 2nd and 3rd Generation but hopefully this should not be the issue.)

I am using the following:
```
service: script.activate_alexa_actionable_notification
data:
  text: Yes or No?
  event_id: alexa_actionable_notification_test
  alexa_device: media_player.echo
```

**BUT:** I can successfully test the skill both …

1. … in the Alexa Simulator in the Developer Console, open the skill with its invocation name and it gives me the correct phrase.
2. … via an Echo by asking “Alexa, open [invocation name]”. Then, the Echo asks me exactly the text which I previously (unsuccessfully) tried to use via the script. I can also follow the response in the developer tools, listening to the `event alexa_actionable_notifications`.

Example:
```
event_type: alexa_actionable_notification
data:
  event_id: alexa_actionable_notification_test
  event_response: ResponseYes
  event_response_type: ResponseYes
origin: REMOTE
time_fired: "2023-12-03T19:13:24.452586+00:00"
context:
  id: 01HGRHK0F44CTJK0P8BQ5VMN1G
  parent_id: null
  user_id: 221efa77d2fd46ffad12ceafac762ee1
```

My current workaround is the following:
- I set up a routine in the Alexa app which says to Alexa the phrase “open [invocation name]”.
- Whenever I want to use Alexa Actions, I first activate `script.activate_alexa_actionable_notification` to send the text to the skill (but nothing happens) and then start the Alexa routine above via HA. This way, I get the correct `event_response` with which I can proceed with my automations.

This works but it is of course just a mere workaround …

Setup:

- latest version of Alexa Actions: v0.10.1
- I imported the skill from the Github repository https://github.com/keatontaylor/alexa-actions.git 
- latest version of Alexa Media Player v4.8.0 installed
- connected via NabuCasa
- language: German
- hosting region: EU (Ireland)
- use of a long lived token
- In the Alexa Developer Console, via Test Development the skill can be reached and gives the correct response phrase.
- The skill is listed in the Alexa app.
- I am using multiple Echo Dots (“just” 2nd and 3rd generation devices but I doubt that this is the issue) and of course the volume is up. The issue is the same with all of the devices.

### Version

v0.10.1

### What Alexa device are you using?

Echo

### What other Alexa device are you using?

Echo Dot 2nd and 3rd generation
