### ISSUE TITLE
Requesting help with the "Installing the script" into home assitand 

### ISSUE THREAD

**Issue by MaximusgottTalos** [keatontaylor/alexa-actions#219]
Context:  I'm a new guy on the comunity and im still learning thw basics, i follow the steps on the wiki and all seams going well i manage to confirm that amazon skill reach HA but on the 4th step when HA is trying to comunicated with Alexa i got stuck, i copy paste the suggested script and change the skill ID but HA keeps showing this error 
![imagen_2024-01-07_162414193](https://github.com/keatontaylor/alexa-actions/assets/155914304/a8229fe0-1aa1-43cf-8cf6-9b564e89c33b)

The guide mention code must be on  "/config/scripts.yaml" I assume it should be on settings > Automations & scenes > scripts 

this is the code: 
```YAML
activate_alexa_actionable_notification:
  alias: activate_alexa_actionable_notification
  description: Activates an actionable notification on a specific echo device
  fields:
    text:
      description: The text you would like alexa to speak.
      example: 'What would you like the thermostat set to?'
    event_id:
      description: Correlation ID for event responses
      example: 'ask_for_temperature'
    alexa_device:
      description: Alexa device you want to trigger
      example: 'media_player.bedroom_echo'
    suppress_confirmation:
      description: Set true if you want to suppress 'okay' confirmation
      example: 'true'
  sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}"}'
    - service: media_player.play_media
      data_template:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: amzn1.ask.skill.bbc326a4-381c-4913-9ca5-f45bc8bfcd7f
  mode: single


```
