### ISSUE TITLE
Advanced actionable notification 

### ISSUE THREAD

**Issue by shedman214** [keatontaylor/alexa-actions#229]
I’m trying to test out my first advanced actionable notification. I followed all the steps  AdvancedFeatures. i’m setting up for my tv to select the source i choose when turned. so farr nothing happens. can i get help on what i’m doing wrong

```
alias: Samsung Source Select
description: Asking which I would like to view
trigger:
  - platform: state
    entity_id:
      - media_player.samsung_tv
    to: "on"
    id: Sasmung TV
  - platform: event
    event_type: alexa_actionable_notification
    id: Source Choice
    event_data:
      event_type: alexa_actionable_notification
      event_data: null
      event_id: alexa_notification_media_tv_select
condition:
  - condition: state
    entity_id: person.animeking
    state: home
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Sasmung TV
        sequence:
          - service: script.activate_alexa_actionable_notification
            metadata: {}
            data:
              text: >-
                I noticed the TV was turned on, what would you like to play,
                Netflix, Youtube TV or Plex?
              event_id: alexa_notification_media_tv_select
              alexa_device: media_player.animeking_echo_dot
    alias: TV Choice
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Source Choice
        sequence:
          - service: media_player.select_source
            target:
              entity_id: media_player.samsung_tv
            data:
              source: "{{ trigger.event.data.event_response }}"
mode: single
```
