### ISSUE TITLE
Where should I put the script? 

### ISSUE THREAD

**Issue by CollaVinilica** [keatontaylor/alexa-actions#23]
Where am I supposed to add the script described in the "Setting up your first actionable notification" wiki since if I copy and paste it in the scrips.yaml it just fucks up home assistant and I get a notification that the integration script can't work due to "invalid config"?

**Comment by steve-gombos** [comment]
Depends on your configuration.yaml.  Should more than likely go into the scripts.yaml file in the root of your configuration directory for most cases.  If you have `default_config:` in your configuration.yaml, then that should be all you need.  If not, then you will need something like `script: !include scripts.yaml` in your configuration.yaml to make sure the scripts are loaded.  If you do it this way, you would omit the first like in the example for `script:`.

**Comment by CollaVinilica** [comment]
Hi, i do have script: !include scripts.yaml in the configuration.yaml file, if I edit the scripts.yaml file by copying and pasting the script  described in the "Setting up your first actionable notification" wiki I get the invalid config error. The scripts I have in the scripts.yaml were created in the home assistant UI and they all start 

'1586532886482':
  alias: Script Name
  sequence:
  - data:

not at all like the script posted in the wiki. What am I missing here? Even if I clear the scripts.yaml file and I paste in it ONLY the script in the wiki I keep getting the invalid config error.

**Comment by steve-gombos** [comment]
Try pasting this in.  I have it in my scripts.yaml.

```
activate_alexa_actionable_notification:
  alias: Notifications - Activate Alexa Action
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: 'The text you would like alexa to speak.'
    event_id:
      description: 'Correlation ID for event responses'
    alexa_device: 
      description: 'Alexa device you want to trigger'
  sequence:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.alexa_actionable_notification
      value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
  - service: media_player.play_media
    data_template:
      entity_id: "{{ alexa_device }}"
      media_content_type: skill
      media_content_id: !secret alexa_actions_skill
```
