### ISSUE TITLE
sample script activate_alexa_actionable_notification fails validation in VSCode

### ISSUE THREAD

**Issue by schoenof** [keatontaylor/alexa-actions#31]
script:
  activate_alexa_actionable_notification:

fails validation in VSCode (connected to HA) because "example: " is expected under each of the fields (text, event_id, and alexa_device)...

I had to modify it like below to pass the validation (although it still works even without passing validation)...

```
activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: 'The text you would like alexa to speak.'
      example: just to pass validation
    event_id:
      description: 'Correlation ID for event responses'
      example: just to pass validation
    alexa_device: 
      description: 'Alexa device you want to trigger'
      example: just to pass validation
  sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
    - service: media_player.play_media
      data_template:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: <Your Skill ID>

```
