### ISSUE TITLE
NumericResponse Not Working

### ISSUE THREAD

**Issue by stringy92** [keatontaylor/alexa-actions#40]
I have tried to setup a numeric response, so i am able to adjust the temperature of the climate, however when i say "40", it doesn't trigger the next automation.

```yaml

  - alias: Hot Tub On Automation
    # initial_state: on
    trigger:
      - platform: state
        entity_id:
          - input_boolean.hot_tub
        to: 'on'
    action:
      - service: script.activate_alexa_actionable_notification
        data_template:
          text: 'What Temperature would you like the hot tub set too'
          event_id: 'actionable_notification_turn_on_hot_tub'
          alexa_device: 'media_player.kitchen_dot'
```

```yaml
  - alias: Numeric Response to Hot Tub.
    trigger:
      platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_turn_on_hot_tub
        event_response_type: ResponseNumeric

    action:
      - service: climate.set_temperature
        entity_id: climate.spa
        data: 
          temperature: "{{ trigger.event.data.event_response }}"
```

As mentioned on the discord, i am able to amend the automation so ResponseYes & ResponseNo are working fine. However Numerical response are not being picked up. Alexa responds with "Okay" after stating a number but the second automation is not triggered
