### ISSUE TITLE
Account linking error

### ISSUE THREAD

**Issue by sesapriv** [keatontaylor/alexa-actions#49]
Hello,

I have been trying to solve a problem I have with account linking by reading other threads but not able to find a solution. Not sure where to debug. I have tried to re-create the skill numerous times in different regions.

Error when trying to link account.

We were unable to link alexa notifications at this time.

Nothing interesting in hassio logs.

Skill region: US
Redirect url: https://pitangui.amazon.com/

**Comment by 1kohm** [comment]
Hallo, 

today I've setup new custom skill according to wiki form this project and my HA is reachable without port :8123. I'm facing very similar issue with account linking. I'm not using HA TOKEN as auth method. I'm using other skills on amazon alexa and they're working.

Help appreciated. 

Best

**Comment by danielbrunt57** [comment]
I just had to re-link my skill today as I believe I may have accidently deleted the refresh token and it was failing to link.  I had originally linked it a long time ago and I think I implemented the HA `trusted_networks:` auth provider after that.  The solution was to remove `trusted_networks:`, restart HA and I could then link my account.  I added `trusted_networks:` back to the config but as the 2nd option and I could still link my account.  So if you are using both `homeassitant:` and `trusted_networks:` as `auth_providers:`, either remove `trusted_networks:` and link your account or make sure `homeassistant:` is listed first...
```
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.16.0.0/12
        - 192.168.1.0/24
        - 127.0.0.1
      allow_bypass_login: true
```
