### ISSUE TITLE
Saying "Alexa, Open Custom Actions" Required

### ISSUE THREAD

**Issue by Pashovski** [keatontaylor/alexa-actions#54]
It's working if I say, "Open custom actions", but otherwise it won't. Everyone is saying this is really easy, so I'm thinking maybe there is a problem with my code. I've noticed in the Home Assist Logs i have some variation of this:

19:13:07 activate_alexa_actionable_notification started (Me)
19:13:07 activate_alexa_actionable_notification turned on (Me)
19:13:07 Alexa Actionable Notification Holder changed to {"text": "", "event": ""} (Me)
19:13:09 activate_alexa_actionable_notification turned off

Here is my code for the automation: https://hastebin.com/aziyekaday.cs

```
- alias: Bedroom door left open for 5 mins
  trigger:
    platform: state
    entity_id: binary_sensor.wyzesense_779c36ac
    to: 'on'
    for:
      minutes: 1
  action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: The bedroom door has been open for 5 mins, would you like me to turn the
        light off?
      event_id: actionable_notification_door_left_open
      alexa_device: media_player.dining_room_echo
  id: 72626d73bda4458288c71eba5e0cf8e5
- alias: Turn off light via actionable notificaiton
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_door_left_open
      event_response_type: ResponseYes
  action:
  - service: light.turn_off
    entity_id: light.master_bedroom_ceiling_fan_light
```
And the script:
```
activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: 'The text you would like alexa to speak.'
      example: 'What would you like the thermostat set to?'
    event_id:
      description: 'Correlation ID for event responses'
      example: 'ask_for_temperature'
    alexa_device: 
      description: 'Alexa device you want to trigger'
      example: 'media_player.dining_room_echo'
  sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
    - service: media_player.play_media
      data_template:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: <amzn1.ask.skill.a71d6d42-7994-4a1a-91a3-bad37c4a7b5b>
```
