### ISSUE TITLE
Error: Invalid client id or redirect url

### ISSUE THREAD

**Issue by poudenes** [keatontaylor/alexa-actions#61]
Hello All,

Tried to build this custom skill. My HA is accessible using https://<mydomain> with port 443.
Im using latest Alexa Media Player : v2.11.2
HA version: 0.114.4

 I have a line in configuration file for Alexa:
alexa: 
  smart_home:
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id_smart_home_messaging
    client_secret: !secret alexa_client_secret_smart_home_messaging

This is working ok.  Alexa Media Player I can use for all my announcements.

But when I want link the new custom_skill part I get the error:
```
Error: Invalid client id or redirect url
```

When I disable account link and put a long live token to the script
Run a automation (when switch turn on ask something):

```
- alias: "TEST - Alexa Custom Skills"
  trigger:

    platform: state
    entity_id: switch.newkaku_014e5906_a
    to: "on"

  action:
    service: script.activate_alexa_actionable_notification
    data_template:
      text: "The test switch is on for more then 1 minute. Do you want me to turn it off?"
      event_id: "actionable_notification_lock_left_unlocked"
      alexa_device: media_player.this_device
```
script:

```
activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: 'The text you would like alexa to speak.'
      example: 'What would you like the thermostat set to?'
    event_id:
      description: 'Correlation ID for event responses'
      example: 'ask_for_temperature'
    alexa_device:
      description: 'Alexa device you want to trigger'
      example: 'media_player.bedroom_echo'
  sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
    - service: media_player.play_media
      data_template:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: amzn1.ask.skill.e82dbcad-7eca-4c61-XXXXXXXXXXXXXXXXXX
```

input text:

```
alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
```

Then my phone is responding only with:
Welcome, you can say Hi or Help. Which would you like to try?

When I do nothing Alexa Ask me this 2 times then stop

WHen i change the media_player to my Echo Dot. Then no speech at all will be heared
