### ISSUE TITLE
Skill only work inside the Amazon Alexa App when using the App

### ISSUE THREAD

**Issue by poudenes** [keatontaylor/alexa-actions#65]
Hi All,

The command : open custom actions is only work when using my iOS app.
When I ask Alexa Echo Dot to open it she say there are few skill that can be open.

I don't get the message:

"This is a test of the alexa actions custom skill. Did it work?"

When I do a action inside HA and send the info to Alexa App device the speak screen come up. nothing happen then its gone again and back to the app

```
- alias: "TEST - Alexa Custom Skills"
  trigger:

    platform: state
    entity_id: switch.newkaku_014e5906_a
    to: "on"

  action:
    service: script.activate_alexa_actionable_notification
    data_template:
      text: "The test switch is on for more then 1 minute. Do you want me to turn it off?"
      event_id: "actionable_notification_lock_left_unlocked"
      alexa_device: media_player.this_device
```
