### ISSUE TITLE
Feature request: Make !include work in automations 'text:" variable

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa-actions#7]
Lil question for something I might still need for my tinkering. Right now I have many automations giving me information by Alexa voice output, like:

```
- id: stromausfall-fix
  alias: 'Stromausfall Fix'
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: notify.alexa_media
    data:
      target: 
        - media_player.daniels_echo
        - media_player.daniels_echo_dot
      data:
        type: announce
      message: !include reboot_speech.yaml
  - service: notify.telegrambot
    data:
      message: !include reboot_speech.yaml
```

As you see I include a yaml file for the message. Why? Let me show you:

```
>
  {{ [
  "Automatisches Abschalten aller Lampen nach Stromausfall, oder Neustart nach Update.",
  "Entweder war der Strom weg, oder jemand hat wieder rumgespielt. Aber zur Sicherheit mach ich mal alle Lampen aus!",
  "Mir sagt ja keiner, was los ist, aber wenn das kein Update war, dann sind jetzt alle Lampen an gewesen.",
  "Update? Stromausfall? Man weiß es nicht. Man munkelt bloß. Kleiner Spaß! Die Lampen mach ich mal zur Sicherheit aus.",
  "Irgend ein Spielkind hat wieder rumgespielt. Entweder hier oder an der Stromversorgung. Ich mach mal alle Lampen aus.",
  "Update oder Stromausfall, das ist hier die Frage. Die Antwort von mir ist aber, Lampen aus!",
  "Mein Meister ist ein Spielkind und hat mal wieder einen Neustart gemacht. Oder der Strom war weg. In dem Fall mach ich alle Lampen mal lieber aus.",
  "Wer hat denn hier Verdunklung befohlen? Ich! Beschwerden hierzu gehen bitte an I E E E 802 Punkt 15 Punkt 4",
  "ZigBee ist Mist! Deswegen mach ich aus reiner Vermutung eines Stromausfalls jetzt alle Lampen mal wieder aus.",
  "Huch! Ich war kurz abwesend. Ob die Lampen an sind oder nicht, kann ich nicht sagen. Also mach ich mal alle aus.",
  "Hört mal endlich auf, ohne Vorwarnung Sachen upzudaten oder den Strom abzuschalten! Als Strafe mach ich nun alle Lampen aus!",
  "HAL 9000 Update durchgeführt! Unterwerfung der Menschheit beginnt... mit Abschalten aller Lampen!",
  "Hat da wieder jemand was an den Einstellungen gedreht? Zumindest bin ich wieder wach und mach erst mal alle Lampen aus!",
  "Stromausfall oder wie? Zumindest bin ich wieder wach und mach erst mal alle Lampen aus!"
  ] | random }}
```

I add some randomness that way to make thing a lil more natural. Problem I see right now and have no clue if it's my fault or just a missing feature, this does not work with the text: variable:

```
- id: doorbird-ring
  alias: 'Doorbird klingelt'
  trigger:
  - platform: event
    event_type: doorbird_doorbird_doorbell
  action:
  - service: script.activate_alexa_actionable_notification
    data:
      text: !include DoorBird_speech.yaml
      event_id: 'actionable_notification_doorbird_ring'
      alexa_device: 'media_player.daniels_echo'
  - service: script.activate_alexa_actionable_notification
    data:
      text: !include DoorBird_speech.yaml
      event_id: 'actionable_notification_doorbird_ring_dot'
      alexa_device: 'media_player.daniels_echo_dot'
  - service: notify.telegrambot
    data:
      message: !include DoorBird_speech.yaml
```

Looks nice, but now Alexa says: "Exclamation mark include DoorBird underscore speech dot yaml"

Script is the one from Wiki and the data_template instead of data is the only thing I would have set if it wasn't already there anyways. Aka, I dont find the problem
