### ISSUE TITLE
New HA update, broken the script!

### ISSUE THREAD

**Issue by sp3cialck** [keatontaylor/alexa-actions#74]
After updating to the last HA version, i'm having an issue with the data_template: 

2020-12-06 19:20:36 ERROR (MainThread) [homeassistant.components.script.activate_alexa_actionable_notification] activate_alexa_actionable_notification: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['data_template']
2020-12-06 19:20:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140671085308944] extra keys not allowed @ data['data_template']

**Comment by julianrinaldi** [comment]
I'm setting this up for the first time and I'm currently having this issue as well. Home Assistant 1.0.0b1

**Comment by sp3cialck** [comment]
> I'm setting this up for the first time and I'm currently having this issue as well. Home Assistant 1.0.0b1

It was working perfectly for months, after updating to the 2020.12.6, crashed... sure HA changed the core changing how the templates works! Maybe the script has to be updated to work again, but i'm waiting  for somebody that knows how to, or Keaton Taylor comes and give us some infos!

**Comment by julianrinaldi** [comment]
I tried added it directly to my scripts.yaml instead of doing it through the Home Assistant UI and it allows you to do it this way. I assume you already had the script saved. Once adding it, it worked a few times, but now I can see my Echo Show being activated, but Alexa doesn't actually say anything. So I assume it's an issue with the script.

**Comment by julianrinaldi** [comment]
Now I'm not sure. I haven't changed anything, and it's working. So I wonder if there was a temporary issue with Amazon or something.

**Comment by sp3cialck** [comment]
They altered how the templates works, now we don't have to use the data_template: , just remove it from the script!

**Comment by julianrinaldi** [comment]
I'm confused as to which part of the script should we remove.

```
activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: 'The text you would like alexa to speak.'
      example: 'What would you like the thermostat set to?'
    event_id:
      description: 'Correlation ID for event responses'
      example: 'ask_for_temperature'
    alexa_device: 
      description: 'Alexa device you want to trigger'
      example: 'media_player.bedroom_echo'
  sequence:
    - service: input_text.set_value
      data:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
    - service: media_player.play_media
      data:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: amzn1.ask.skill.***********************
```

Do we just delete the lines where it says data?

**Comment by sp3cialck** [comment]
> I'm confused as to which part of the script should we remove.
> 
> ```
> activate_alexa_actionable_notification:
>   description: 'Activates an actionable notification on a specific echo device'
>   fields:
>     text:
>       description: 'The text you would like alexa to speak.'
>       example: 'What would you like the thermostat set to?'
>     event_id:
>       description: 'Correlation ID for event responses'
>       example: 'ask_for_temperature'
>     alexa_device: 
>       description: 'Alexa device you want to trigger'
>       example: 'media_player.bedroom_echo'
>   sequence:
>     - service: input_text.set_value
>       data:
>         entity_id: input_text.alexa_actionable_notification
>         value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
>     - service: media_player.play_media
>       data:
>         entity_id: "{{ alexa_device }}"
>         media_content_type: skill
>         media_content_id: amzn1.ask.skill.***********************
> ```
> 
> Do we just delete the lines where it says data?

The problem isn't in the script itself (my bad, but it was working this way before), the problem was i edited a script to call the service using the ui, and so looked it like:

```
service: input_text.set_value
data:
  data_template:
    entity_id: input_text.alexa_actionable_notification
    value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'

```
I don't know if i followed other tutorial or fork... but removing the line after data: it's working again!

With you script it should be working good!
